### ISSUE TITLE
Uses an undefined network 'gerdau'

### ISSUE THREAD

**Issue by zdrsoft** [agusnavce/keycloak_example#4]
$ docker-compose up -d
WARNING: The DATABASE_USER variable is not set. Defaulting to a blank string.
WARNING: The DATABASE_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The KEYCLOAK_USER variable is not set. Defaulting to a blank string.
WARNING: The KEYCLOAK_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The REALM variable is not set. Defaulting to a blank string.
WARNING: The CLIENT_ID variable is not set. Defaulting to a blank string.
WARNING: The CLIENT_SECRET variable is not set. Defaulting to a blank string.
WARNING: The ADMIN_USER variable is not set. Defaulting to a blank string.
WARNING: The ADMIN_PASS variable is not set. Defaulting to a blank string.
ERROR: Service "api" uses an undefined network "gerdau"

**Comment by ndrini** [comment]
You can comment the line of the docker-compose about the network "gerdau"

and you should create the missing variables in a .env file at root level
